# Generated by Django 2.1 on 2019-11-17 04:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Unlimited_images/images/')),
                ('image_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_description', models.TextField()),
                ('image_upload_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='type_of_image',
            unique_together={('image_category_type',)},
        ),
        migrations.AlterUniqueTogether(
            name='sub_category_image',
            unique_together={('sub_category_type',)},
        ),
        migrations.AddField(
            model_name='image_store',
            name='image_category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlimited_app.Type_of_Image'),
        ),
        migrations.AddField(
            model_name='image_store',
            name='sub_category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlimited_app.Sub_Category_Image'),
        ),
        migrations.AlterUniqueTogether(
            name='image_store',
            unique_together={('image_id',)},
        ),
    ]
