# Generated by Django 3.0.8 on 2020-08-02 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unlimited_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='myfavorite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mydownload',
            name='images',
            field=models.ManyToManyField(to='unlimited_app.ImageStore'),
        ),
        migrations.AddField(
            model_name='mydownload',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagestore',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlimited_app.FileType'),
        ),
        migrations.AddField(
            model_name='imagestore',
            name='image_tag',
            field=models.ManyToManyField(to='unlimited_app.Tag'),
        ),
        migrations.AddField(
            model_name='imagestore',
            name='sub_category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlimited_app.SubCategory'),
        ),
        migrations.AddField(
            model_name='imagestore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlimited_app.ImageStore'),
        ),
    ]
