# Generated by Django 3.0.7 on 2020-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlimited_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
