# Generated by Django 3.0.7 on 2020-07-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlimited_app', '0002_imagestore_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
    ]
