# Generated by Django 3.0.7 on 2020-07-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlimited_app', '0003_imagestore_ispremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
