# Generated by Django 2.1 on 2019-09-08 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_client_id', models.CharField(max_length=250, null=True)),
                ('facebook_client_id', models.CharField(max_length=250, null=True)),
                ('google_refresh_token', models.TextField(blank=True, null=True)),
                ('facebook_refresh_token', models.TextField(blank=True, null=True)),
                ('google_access_token', models.TextField(blank=True, null=True)),
                ('facebook_access_token', models.TextField(blank=True, null=True)),
                ('google_id_token', models.TextField(blank=True, null=True)),
                ('access_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
